// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    Default: typeof import('./../src/layouts/Default.vue')['default']
    EquipmentBoard: typeof import('./../src/views/modules/EquipmentBoard/index.vue')['default']
    EquipmentList: typeof import('./../src/views/modules/EquipmentBoard/EquipmentList.vue')['default']
    ExclamationCircleFilled: typeof import('@ant-design/icons-vue')['ExclamationCircleFilled']
    Login: typeof import('./../src/views/system/Login.vue')['default']
    MenuFoldOutlined: typeof import('@ant-design/icons-vue')['MenuFoldOutlined']
    MenuUnfoldOutlined: typeof import('@ant-design/icons-vue')['MenuUnfoldOutlined']
    OrganizationConfiguration: typeof import('./../src/views/modules/BasicConfiguration/OrganizationConfiguration/index.vue')['default']
    PageNotFound: typeof import('./../src/views/system/abnormal/PageNotFound.vue')['default']
    PageTab: typeof import('./../src/layouts/PageTab/index.vue')['default']
    QuotaConfiguration: typeof import('./../src/views/modules/BasicConfiguration/QuotaConfiguration/index.vue')['default']
    QuotaDetail: typeof import('./../src/views/modules/EquipmentBoard/QuotaDetail.vue')['default']
    Root: typeof import('./../src/views/system/Root.vue')['default']
    Sidebar: typeof import('./../src/layouts/Sidebar.vue')['default']
    SparePartsBoard: typeof import('./../src/views/modules/SparePartsBoard/index.vue')['default']
    SyncOutlined: typeof import('@ant-design/icons-vue')['SyncOutlined']
    Test: typeof import('./../src/views/modules/Test.vue')['default']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
  }
}

export { }
